[top]
components : min@AgujaMin
out : VALUE OUT_INCREMENT OUT_DECREMENT
in : TIC IN_INCREMENT IN_DECREMENT
Link : IN_INCREMENT IN_INCREMENT@min
Link : IN_DECREMENT IN_DECREMENT@min
Link : TIC TIC@min
Link : OUT_INCREMENT@min OUT_INCREMENT
Link : OUT_DECREMENT@min OUT_DECREMENT
Link : VALUE@min VALUE
